Feat/mutation
Yedidya10/musical-soulmate pull request #1
Opened 2023-04-28 21:34 UTC by alinauroz

Adds mutation for creating a subscriber

2023-04-28 22:09 UTC, alinauroz commented on graphql/types/subscriber.ts
> +});
This is the input type of addSubscriber mutation. It accepts three fields i-e email, language and country.

2023-04-28 22:10 UTC, alinauroz commented on graphql/types/subscriber.ts
>      // createdAt: t.expose('createdAt', { type: 'Date' }),
Subscriber did not have country and language in its schema but it was present in prisma schema. So I also added it here

2023-04-28 22:11 UTC, alinauroz commented on graphql/types/subscriber.ts
> +    type: 'Subscriber',
This is the mutation to add subscriber. Its type is Subscriber which means it returns an object of type Subscriber.

2023-04-28 22:12 UTC, alinauroz commented on graphql/types/subscriber.ts
> +    },
Here the input arguments of this mutation are mentioned. CreateSubscriberInput is defined above.

2023-04-28 22:12 UTC, alinauroz commented on graphql/types/subscriber.ts
> +);
This is the resolver of this mutation. When this mutation is called it created a record is database.

2023-04-28 22:13 UTC, alinauroz commented on graphql/types/user.ts
> -builder.prismaObject('Subscriber', {
Subscriber object was defined twice so I commented one.

2023-04-30 17:56 UTC, Yedidya10 requested changes
Please see the comment I wrote.

2023-04-30 17:56 UTC, Yedidya10 commented on graphql/builder.ts
> -import { DateResolver } from 'graphql-scalars'
It is important that the createdAt and updatedAt are recorded in a database. Please add them to the mutation process.

2023-04-30 18:01 UTC, Yedidya10 commented on graphql/types/subscriber.ts
> +});
I also referred to the following comment in the previous commit:
It is important that the createdAt and updatedAt are recorded in a database. Please add them to the mutation process.

2023-04-30 18:05 UTC, Yedidya10 requested changes
I also referred to the following comment in the previous commit

2023-04-30 18:07 UTC, Yedidya10 approved these changes
It looks okay

2023-04-30 18:10 UTC, Yedidya10 approved these changes
it looks good

2023-04-30 18:16 UTC, Yedidya10 approved these changes
it looks good

2023-04-30 18:48 UTC, alinauroz commented on graphql/types/subscriber.ts
> +});
createdAt and updatedAt are recorded. There default values are set in the model in prisma schema.

2023-05-03 11:29 UTC, merged